name: Send Discord Blacklist Notification

on:
  push:
    branches: [ main, master ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Blacklist Embed via Curl
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [
              {
                "title": "BLACKLISTED GROUPS",
                "color": 15548997,
                "description": "These are all the blacklisted groups, if you are in any of them, you may not join our game and therefore you may not earn any position.",
                "fields": [
                  {
                    "name": "TGA Owned by: Dev_Infldspro1",
                    "value": "[TGA Link](https://www.roblox.com/communities/35888244/TGA-The-Grand-Army#!/about)\nReason of blacklist: Deleted 2 CT maps, took one of them for his own game, made 3 alts to try and get more assets, scammer in a lot of other servers, steal GFX and thumbnails from other groups too."
                  },
                  {
                    "name": "TNO Owned by: ezra_james864",
                    "value": "[TNO Link](https://www.roblox.com/communities/13538854/TGE-The-New-Order#!/about)\nReason of blacklist: User has DM advertised multiple officers in CT, once I found out, he just blacklisted CT and banned the CT Lead Command from his group."
                  },
                  {
                    "name": "GATR Owned by: TheBigPrisoner",
                    "value": "[GATR Link](https://www.roblox.com/communities/7070554/Grand-Army-of-the-Republic#!/about)\nReason of blacklist: Prisoner deleted the Clone Assassin server, nuked the game as a developer. After that, he spread false information and leaked all CT maps and assets to 300+ members in his group + in CT."
                  }
                ],
                "footer": {
                  "text": "**This embed was generated by a server administrator. Exercise caution when interacting with any links.**"
                }
              }
            ]
          }' \
          "${{ secrets.DISCORD_WEBHOOK }}"
